export const COMMAND_DESCRIPTIONS = {
  transcribe: "Transcreve um áudio em texto",
  fig: "Cria uma figurinha a partir de uma imagem ou vídeo",
  img: "Envia a imagem original de uma figurinha",
  delete: "Deleta uma mensagem",
  pussy: "Envia uma imagem NSFW de pussy",
  ass: "Envia uma imagem NSFW de bunda",
  dick: "Envia uma imagem NSFW de pênis",
  futa: "Envia uma imagem NSFW de futanari",
  hentai: "Envia uma imagem NSFW de hentai",
  yaoi: "Envia uma imagem NSFW de yaoi",
  boobs: "Envia uma imagem NSFW de seios",
  gay: "Envia uma imagem NSFW gay",
  r34: "Busca uma imagem no Rule34 com a tag especificada",
  r34random: "Envia uma imagem aleatória do Rule34",
  menu: "Mostra o menu de comandos disponíveis",
  nsfw: "Mostra o menu de comandos NSFW",
  groups: "Lista os grupos",
  pokemon: "Captura um Pokémon aleatório",
  pokedex: "Mostra a Pokédex do usuário",
  companion: "Escolhe um Pokémon como companheiro",
  trade: "Inicia uma troca de Pokémon",
  accepttrade: "Aceita uma proposta de troca",
  rejecttrade: "Rejeita uma proposta de troca",
  pendingtrades: "Lista as trocas pendentes",
  sacrificar: "Sacrifica um Pokémon para reduzir o tempo de espera",
  sacrificiostatus: "Mostra o status de sacrifício",
  pokesystem: "Mostra informações sobre o sistema de Pokémon",
  levelsystem: "Ativa ou desativa o sistema de níveis",
  level: "Mostra o nível atual do usuário",
  toprank: "Mostra o ranking dos usuários",
  resetcapturetime: "Reseta o tempo de captura (admin)",
  captureall: "Captura todos os Pokémon disponíveis",
  pokerarity: "Lista Pokémon por raridade",
  aiinterpreter: "Ativa ou desativa o interpretador AI"
};
